Add files via upload
VasilTsimashenka/automation pull request #2
Opened 2022-04-30 08:29 UTC by VasilTsimashenka

2022-04-30 10:14 UTC, VasilTsimashenka commented
![xpath](https://user-images.githubusercontent.com/93875949/166101395-78a4f9a7-a7c0-42c5-b0d7-18235caec571.png)

2022-04-30 10:14 UTC, VasilTsimashenka commented
![Screenshot_4](https://user-images.githubusercontent.com/93875949/166101447-d2c868e3-b0a4-40b4-b033-d937de428312.png)

2022-04-30 10:15 UTC, VasilTsimashenka commented
![Screenshot_5](https://user-images.githubusercontent.com/93875949/166101459-e46f75b7-5a4f-42b7-befa-d3a93d4aa291.png)

2022-05-04 14:25 UTC, Kirill-Simonovich requested changes

2022-05-04 14:25 UTC, Kirill-Simonovich commented on PULL_REQUEST_TEMPLATE.md
> +## Title
delete this file

2022-05-04 14:25 UTC, Kirill-Simonovich commented on auto_assign.yml
> +# Set to true to add reviewers to pull requests
delete this file

2022-05-04 14:25 UTC, Kirill-Simonovich commented on src/test/java/TestCases.java
> +        sleep(5000);
Delete all sleep()

2022-05-10 05:19 UTC, Kirill-Simonovich requested changes

2022-05-10 05:19 UTC, Kirill-Simonovich commented on src/test/java/TestCases.java
> +        $(".first-item-of-mobile-line.last-mobile-line > div > div.right-block > div." +
это самый короткий селектор?

2022-05-10 05:19 UTC, Kirill-Simonovich commented on src/test/java/TestCases.java
> +        $(".last-mobile-line > div > div.left-block > div > a.product_img_link").hover();
это самый короткий селектор?

2022-05-10 05:19 UTC, Kirill-Simonovich commented on src/test/java/TestCases.java
> +        $("#block_top_menu > ul > li:nth-child(2) > ul > li:nth-child(3) > a").click();
это самый короткий селектор?

2022-05-10 05:19 UTC, Kirill-Simonovich commented on src/test/java/TestCases.java
> +        $("#block_top_menu > ul > li:nth-child(1) > ul > li:nth-child(1) > ul > li:nth-child(2) > a").click();
это самый короткий селектор?

2022-05-10 05:19 UTC, Kirill-Simonovich commented on src/test/java/TestCases.java
> +        $("#criterions_list > li > div.star_content > div:nth-child(7) > a").click();
это самый короткий селектор?

2022-05-10 05:19 UTC, Kirill-Simonovich commented on src/test/java/TestCases.java
> +        $("#block_top_menu > ul > li:nth-child(2) > ul > li:nth-child(1) > a").click();
это самый короткий селектор?

2022-05-10 17:55 UTC, VasilTsimashenka commented on src/test/java/TestCases.java
> +        $("#block_top_menu > ul > li:nth-child(2) > ul > li:nth-child(1) > a").click();
получается, что так(

2022-05-18 10:58 UTC, Kirill-Simonovich approved these changes

2022-05-23 15:29 UTC, merged